Main svc
Sad-Duck/java-explore-with-me pull request #3
Opened 2023-03-10 16:12 UTC by Sad-Duck

2023-03-13 19:44 UTC, Frilock requested changes
Добрый вечер, комментарии в коде

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/categories/dto/NewCategoryDto.java
> +    Long id;
Модификатор приватный

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/categories/model/Category.java
> +@Table(name = "categories", schema = "public")
public дефолтная схема ее можно не указывать

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/categories/repository/CategoryRepository.java
> +@Repository
Смотрите, над интерфейсами нет смысла ставить аннотации помечающих класс бином, главное чтоб аннотация стояла над реализацией данного интерфейса.

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/categories/service/CategoryServiceAdmin.java
> +    @Transactional
Аналогично: Смотрите, над интерфейсами нет смысла ставить аннотации помечающих класс бином, главное чтоб аннотация стояла над реализацией данного интерфейса.

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/categories/service/impl/CategoryServiceAdminImpl.java
> +        finder.findCategory(catId); //проверить на наличие по id
Нужно тогда реализовать метод какой то: existCategoryById. Этот будет путать

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/categories/service/impl/CategoryServicePublicImpl.java
> +@Slf4j
Аннотация есть, а логгер не используется

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilations/dto/CompilationDto.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
а почему бы просто приватный модификатор не проставить?)

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilations/dto/NewCompilationDto.java
> +    List<Long> events;
Просто в одних Дтошках у вас есть модификаторы в других нет, делайте единообразно

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilations/mapper/CompilationMapper.java
> +
лишняя пустая строка

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilations/mapper/CompilationMapper.java
> +@RequiredArgsConstructor
Лишняя аннотация, у вас нет полей в классе она не нужна

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilations/mapper/CompilationMapper.java
> +
Лишняя пустая строка

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilations/service/impl/CompilationServiceAdminImpl.java
> +        if (updateDto.getPinned() != null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/events/mapper/EventMapper.java
> +@RequiredArgsConstructor
Лишняя аннотации

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/events/model/EventSort.java
> +@RequiredArgsConstructor
Лишняя аннотация

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/events/model/Location.java
> +public class Location {
А не нужна аннотация table? У Вас без нее работает?

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/events/repository/EventRepository.java
> +    @Query("select event from Event event " +
По моему можно без аннотации обойтись и уложиться в имени запроса

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/events/service/impl/EventServiceAdminImpl.java
> +        if (!event.getState().equals(State.PENDING)) {
enum поля правильнее сравнивать через стандартные операторы != и ==, работать будет в любом случае, но стандартные операторы как минимум быстрее

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/events/service/impl/EventServicePublicImpl.java
> +    public List<EventFullDto> getEventsWithFilters(EventPublicSearch ev, String ip) {
странное сокращение ev, давайте назовем нормально

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/requests/model/ParticipationRequest.java
> +@Table(name = "participation_requests", schema = "public")
схему можно не указывать

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/java/ru/practicum/users/service/impl/UserServiceAdminImpl.java
> +//TODO исключение
Нужно убрать todo либо исправить что хотели

2023-03-13 19:44 UTC, Frilock commented on main-service/src/main/resources/schema.sql
> +    description        VARCHAR(7000)                           NOT NULL,
Указанный тут размер нужно указывать также в аннотации column, чтобы не приходилось каждый раз лезть в скрипты чтобы узнать размер, кроме того там можно указывать дополнительные флаги, например, nullable = false и т.д.

2023-03-13 19:44 UTC, Frilock commented on stats/stats-client/pom.xml
> +<!--    <build>-->
Закомментированный код оставлять не нужно, либо удалите, либо верните

2023-03-13 19:44 UTC, Frilock commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +@Slf4j
Не вижу использования логгера

2023-03-14 13:50 UTC, Sad-Duck commented on main-service/src/main/java/ru/practicum/events/model/Location.java
> +public class Location {
работает! у меня вышло так, что широта и долгота в базе данных сохраняются в сущности ивента, а не в своей отдельной таблице. Так можно?:)

2023-03-14 13:55 UTC, Sad-Duck commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +@Slf4j
там был один лог в методе post:) на всякий случай добавил второй

2023-03-15 18:09 UTC, Frilock requested changes
Добрый вечер, написал еще ряд небольших комментариев

2023-03-15 18:09 UTC, Frilock commented on main-service/src/main/java/ru/practicum/categories/service/CategoryServicePublic.java
> +    CategoryDto getCategory(Long catId);
Можно добавить ById

2023-03-15 18:09 UTC, Frilock commented on main-service/src/main/java/ru/practicum/categories/service/impl/CategoryServiceAdminImpl.java
> +    @Transactional
Над всеми методами сервиса стоят аннотация транзакции, поэтому можно ее повесить над классом, а с методов убрать

2023-03-15 18:09 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilations/controller/CompilationControllerAdmin.java
> +            @RequestBody @Validated NewCompilationDto newCompilationDto) {
Вместо Validated должна быть аннотация Valid

2023-03-15 18:09 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilations/mapper/CompilationMapper.java
> +@Component
А зачем класс делать бином, если у него все методы статические? Либо статическиймодификатор уберите, либо компонент

2023-03-15 18:09 UTC, Frilock commented on main-service/src/main/java/ru/practicum/events/controller/EventControllerPrivate.java
> +            @RequestBody @Validated NewEventDto newEventDto) {
Valid вместо validated

2023-03-15 18:09 UTC, Frilock commented on main-service/src/main/java/ru/practicum/events/mapper/EventMapper.java
> +@Component
а нужен ли вам тут компонент?

2023-03-15 18:09 UTC, Frilock commented on main-service/src/main/java/ru/practicum/events/model/Location.java
> +public class Location {
А вы как планировали? В отдельной таблице или так?
В целом можно.

2023-03-15 18:09 UTC, Frilock commented on main-service/src/main/java/ru/practicum/events/repository/EventRepository.java
> +
Куча пустых строк, оставьте одну

2023-03-15 18:09 UTC, Frilock commented on main-service/src/main/java/ru/practicum/events/service/EventServicePublic.java
> +    @Transactional
Бесполезные аннотации, оставлял вам комментарий об этом

2023-03-15 18:09 UTC, Frilock commented on main-service/src/main/java/ru/practicum/events/service/impl/EventServiceAdminImpl.java
> +    public List<EventFullDto> addViewsFromStatistic(List<Event> events) {
А почему метод публичный? Он используется из вне? Если да, то почему его нет в интерфейсе?

2023-03-15 18:09 UTC, Frilock commented on main-service/src/main/java/ru/practicum/events/service/impl/EventServicePrivateImpl.java
> +        if (event.getState().equals(State.PUBLISHED)) {
Сравнение лучше через стандартный оператор

2023-03-15 18:09 UTC, Frilock commented on main-service/src/main/java/ru/practicum/users/service/impl/UserServiceAdminImpl.java
> +    public ResponseEntity<UserDto> createUser(NewUserRequest newUserRequest) {
Работу с ResponseEntity правильнее перенести в контролер, то есть если нет ошибок то CREATED

2023-03-15 18:09 UTC, Frilock commented on main-service/src/main/java/ru/practicum/util/EwmObjectFinder.java
> +    public EwmObjectFinder(UserRepository userRepository,
А почему тут на ломбок не поменяли? а то везде с ним, а тут без

2023-03-15 18:09 UTC, Frilock commented on main-service/src/main/java/ru/practicum/util/EwmObjectFinder.java
> +                .orElseThrow(() -> new NotFoundException("Пользователь с id - " + id + "не найден"));
не найден сольется с ид, пропустите пробел

2023-03-15 18:09 UTC, Frilock commented on main-service/src/main/java/ru/practicum/util/EwmObjectFinder.java
> +        if (id == null) throw new ValidationException("Id пользователя не указан");
Правильнее обособлять скобками, даже если состоит блок из 1 строки, дабы избегать возможных ошибок по невнимательности

2023-03-15 23:55 UTC, Sad-Duck commented on main-service/src/main/java/ru/practicum/events/model/Location.java
> +public class Location {
Наверное не правильно выразился, я, в общем-то, так и планировал изначально
Координаты в бд сохраняются, всё работает.

2023-03-16 13:26 UTC, Frilock approved these changes
Алексей, принято

2023-03-16 13:34 UTC, merged