feature_comments
Sad-Duck/java-explore-with-me pull request #4
Opened 2023-03-17 20:36 UTC by Sad-Duck

Здравствуйте, на всякий случай хочу коротко описать некоторые нюансы задумки:
На комментарии можно отвечать, а затем по отдельному эндпоинту получать ветку с ответами.

При создании или обновлении события можно поставить флаг "disableComments" тогда комментарии к событию будут отключены. Пользователь не может отключить комментарии если у события они уже есть. Администратор может отключить комментарии всегда, при этом все комментарии события удаляются. 

При удалении пользователя все его комментарии удаляются

2023-03-18 08:01 UTC, Frilock requested changes
Добрый день, все в целом хорошо, идея хорошая. У меня один такой вопрос с репозиторием, где Вы передаете pageble. Разве не логичнее обьект Page возвращать?

2023-03-18 08:01 UTC, Frilock commented on README.md
> +
Вообще было бы здорово, если вы те уточнения (задумка ваша) описали бы сюда в кратце.

2023-03-18 08:01 UTC, Frilock commented on main-service/src/main/java/ru/practicum/comments/controller/CommentControllerAdmin.java
> +    public CommentDto getById(@PathVariable Long id) {
У Вас в данном контролере все остальные методы кроме поиска содержат в название слово comment, предлагаю в 2 метода поиска тоже его добавить, чтобы выглядело единообразно

2023-03-18 08:01 UTC, Frilock commented on main-service/src/main/java/ru/practicum/comments/dto/UpdateCommentRequest.java
> +public class UpdateCommentRequest {
А для чего Вы создаете 2 одинаковых ДТО с разным названием? Если они полностью одинаковые создавать 2 разных объекта нет особого смысла

2023-03-18 08:01 UTC, Frilock commented on main-service/src/main/java/ru/practicum/comments/repository/CommentRepository.java
> +    List<Comment> findByEventId(Long eventId, Pageable pageable);
Тут возникает вопрос, а если Вы используете тут объект pageable, то Вы по идее должны отдавать не просто лист, а объект Page. Расскажите почему сделали именно так?

2023-03-18 20:11 UTC, Sad-Duck commented on main-service/src/main/java/ru/practicum/comments/repository/CommentRepository.java
> +    List<Comment> findByEventId(Long eventId, Pageable pageable);
По невнимательности) Изменил на Page здесь и ещё в нескольких репозиториях

2023-03-19 20:09 UTC, Frilock approved these changes
Принято, молодец, успехов в дальнейшем

2023-03-19 22:00 UTC, merged